name: email-rest-service

services:

  postgres-db:
    image: 'postgres:16.3-alpine'
    container_name: "postgres"
    # Redirect port to be accessible.
    ports:
      - "5432:5432"
    # Bind mound to hidden directory in project.
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    # Set user and password + default DB to use.
    environment:
      - POSTGRES_USER=email-service-user
      - POSTGRES_PASSWORD=fun-email-server
      - POSTGRES_DB=emails
